#include <ESP8266WiFi.h>
#include <BlynkSimpleEsp8266.h>
#include <SimpleTimer.h>
#include <DHT.h>

#define PHOTO A0 // фоторезистор подключен к пину A0
#define DHTTYPE DHT22
#define DHTPIN 4

uint16_t sensor; // объявляем глобальную переменную sensor

int chk;
// You should get Auth Token in the Blynk App.
// Go to the Project Settings (nut icon).
char auth[] = "token"; //insert here your token generated by Blynk

DHT dht(DHTPIN, DHTTYPE, 11); // 11 works fine for ESP8266

SimpleTimer timer;

// This function sends Arduino's up time every second to Virtual Pin (5).
// In the app, Widget's reading frequency should be set to PUSH. This means
// that you define how often to send data to Blynk App.
void sendUptime()
{
  // You can send any value at any time.
  // Please don't send more that 10 values per second.
  Blynk.virtualWrite(10, dht.readTemperature()); //virtual pin
  Blynk.virtualWrite(11, dht.readHumidity()); // virtual pin
  sensor = analogRead(PHOTO);
  Blynk.virtualWrite(V1, sensor);
  delay(2000);
}

void setup()
{
  dht.begin();
  Blynk.begin(auth, "ssid", "password", IPAddress(192,168,X,X)); //insert here your SSID and password

  // Setup a function to be called every second
  timer.setInterval(2000, sendUptime);
}

void loop()
{
  Blynk.run(); // Initiates Blynk
}
